version: 2
notify:
  webhooks:
    - url: https://circledisc-clarity.herokuapp.com/webhook/circle
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image (Vanilla)
          command: docker build -t chinodesuuu/coder:vanilla -t chinodesuuu/coder:latest -f Dockerfile.vanilla .
      - run:
          name: Build Docker Image (OpenShift)
          command: docker build -t chinodesuuu/coder:openshift -f Dockerfile.openshift .
  deploy:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker Image (Vanilla)
          command: docker build -t chinodesuuu/coder:vanilla -t chinodesuuu/coder:latest -f Dockerfile.vanilla .
      - run:
          name: Build Docker Image (OpenShift)
          command: docker build -t chinodesuuu/coder:openshift -f Dockerfile.openshift .
      - run:
          name: Docker Push 
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS &&  docker push chinodesuuu/coder:latest && docker push chinodesuuu/coder:openshift && docker push chinodesuuu/coder:vanilla;
        
workflows:
  version: 2
  scheduled-workflow:
    triggers:
      - schedule:
          cron: "0 0 * * 0"
          filters:
            branches:
              only: release
    jobs:
      - deploy
  build-n-deploy:
    jobs:
      - build
      - deploy:
          requires:
             - build
          filters:
            branches:
               only: release